version: "3.1"

services:
  db:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./pokeData:/data/db
    environment:
      - MONGO_INITDB_DATABASE=Pokemon
    ports:
      - 27017:27017

  redis:
    restart: always
    container_name: redis
    image: redis:alpine
    volumes:
      - ./cacheData:/data
    ports:
      - 6379:6379
